# Generated by Django 4.2.6 on 2023-11-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Blog title')),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('information', models.TextField(verbose_name='First and most important information about the blog')),
                ('main_image', models.FileField(upload_to='blog/main_images/')),
            ],
        ),
    ]
