# Generated by Django 4.2.6 on 2023-11-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Our address')),
                ('phone', models.CharField(max_length=30, verbose_name='Our phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Our email')),
                ('website', models.CharField(max_length=125, verbose_name='Our website')),
            ],
        ),
    ]
