# Generated by Django 4.2.6 on 2023-11-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncludedInThePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Included article in the price')),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('image', models.FileField(upload_to='included_in_the_price/')),
            ],
        ),
    ]
