# Generated by Django 4.2.6 on 2023-11-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Accessory name')),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('type', models.CharField(blank=True, default='Accessories', editable=False, max_length=20)),
                ('price_per_day', models.PositiveIntegerField(verbose_name='Price per 1 day')),
                ('main_image', models.ImageField(upload_to='accessories/main_images/')),
            ],
        ),
    ]
