# Generated by Django 4.2.6 on 2023-11-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tour title')),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('information', models.TextField(verbose_name='Information about the tour')),
                ('main_image', models.FileField(upload_to='tour/main_image/')),
            ],
        ),
    ]
