# Generated by Django 4.2.6 on 2023-11-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.PositiveIntegerField(default=499, verbose_name='Tour price'),
            preserve_default=False,
        ),
    ]
