# Generated by Django 4.2.6 on 2023-11-01 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_tourimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourMoreInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='more_information', to='tour.tour')),
            ],
        ),
    ]
