# Generated by Django 4.2.6 on 2023-11-01 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_tourmoreinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourmoreinformation',
            name='more_information',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='More information'),
            preserve_default=False,
        ),
    ]
