# Generated by Django 4.2.6 on 2023-11-01 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='date_of_creation',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
