# Generated by Django 4.2.6 on 2023-11-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_contactus_date_of_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
