# Generated by Django 4.2.6 on 2023-11-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Question')),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('answer', models.TextField(verbose_name='Answer')),
            ],
        ),
        migrations.CreateModel(
            name='DepositAndInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Question')),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('answer', models.TextField(verbose_name='Answer')),
            ],
        ),
    ]
